# Generated by Django 3.0.5 on 2020-05-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome', '0003_auto_20200504_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='image',
            field=models.ImageField(upload_to='chef/'),
        ),
    ]
