# Generated by Django 3.0.5 on 2020-05-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awesome', '0004_auto_20200504_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'chef', 'verbose_name_plural': 'chefs'},
        ),
    ]
